apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatons-cloud
  namespace: chatons-cloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "cloud-realtime"
spec:
  ingressClassName: nginx
  rules:
    - host: api.chatons.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-api
                port:
                  number: 80
    - host: realtime.chatons.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-realtime
                port:
                  number: 80
