apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatons-cloud
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - cloud-api.yaml
  - cloud-realtime.yaml
  - runtime-headless.yaml
  - pdb.yaml
  - network-policy.yaml
  - cert-issuer.yaml
  - ingress.yaml
  - hpa.yaml
